# Generated by Django 5.1.2 on 2025-11-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_add_user_to_task'),
    ]

    operations = [
    ]
